-- +goose Up

-- Drop forward chain related tables in reverse dependency order
DROP TABLE IF EXISTS forward_chain_rules;
DROP TABLE IF EXISTS forward_chain_nodes;
DROP TABLE IF EXISTS forward_chains;

-- +goose Down

-- Recreate forward_chains table for managing multi-hop forwarding chains
CREATE TABLE forward_chains (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT 'Chain name',
    protocol VARCHAR(10) NOT NULL DEFAULT 'tcp' COMMENT 'Protocol: tcp, udp, both',
    status VARCHAR(20) NOT NULL DEFAULT 'disabled' COMMENT 'Status: enabled, disabled',
    target_address VARCHAR(255) NOT NULL COMMENT 'Final target address',
    target_port SMALLINT UNSIGNED NOT NULL COMMENT 'Final target port',
    remark VARCHAR(500) DEFAULT '' COMMENT 'Optional remark',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,

    UNIQUE INDEX idx_chain_name (name),
    INDEX idx_chain_protocol (protocol),
    INDEX idx_chain_status (status),
    INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Recreate forward_chain_nodes table for chain node definitions
CREATE TABLE forward_chain_nodes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chain_id BIGINT UNSIGNED NOT NULL COMMENT 'Forward chain ID',
    agent_id BIGINT UNSIGNED NOT NULL COMMENT 'Forward agent ID',
    listen_port SMALLINT UNSIGNED NOT NULL COMMENT 'Port to listen on this agent',
    sequence INT NOT NULL COMMENT 'Order in the chain (1-based)',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_chain_node_chain_id (chain_id),
    INDEX idx_chain_node_agent_id (agent_id),
    UNIQUE INDEX idx_chain_node_unique (chain_id, sequence)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Recreate forward_chain_rules table to track rules generated by chains
CREATE TABLE forward_chain_rules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chain_id BIGINT UNSIGNED NOT NULL COMMENT 'Forward chain ID',
    rule_id BIGINT UNSIGNED NOT NULL COMMENT 'Forward rule ID',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_chain_rule_chain_id (chain_id),
    INDEX idx_chain_rule_rule_id (rule_id),
    UNIQUE INDEX idx_chain_rule_unique (chain_id, rule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
